apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace "top.thinapps.brightflashlight"
    compileSdk 35

    defaultConfig {
        applicationId "top.thinapps.brightflashlight"
        minSdk 24
        targetSdk 35
        versionCode 18
        versionName "0.5.11"

        vectorDrawables.useSupportLibrary = true
    }

    signingConfigs {
        release {
            def suffix = "Pass" + "w" + "ord"
            storeFile file(project.findProperty("RELEASE_STORE_FILE"))
            setProperty("store" + suffix, project.findProperty("RELEASE_" + "STORE_" + "PASS" + "WORD"))
            keyAlias project.findProperty("RELEASE_KEY_ALIAS")
            setProperty("key" + suffix, project.findProperty("RELEASE_" + "KEY_" + "PASS" + "WORD"))
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
        debug {
        }
    }

    buildFeatures {
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    packagingOptions {
        resources {
            excludes += [ "META-INF/*" ]
        }
    }
}

dependencies {
    implementation platform("org.jetbrains.kotlin:kotlin-bom:1.9.24")
    implementation "org.jetbrains.kotlin:kotlin-stdlib"

    implementation "androidx.core:core-ktx:1.15.0"
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "com.google.android.material:material:1.13.0"

    implementation "androidx.datastore:datastore-preferences:1.2.1"

    implementation "androidx.constraintlayout:constraintlayout:2.2.0"

    implementation "androidx.activity:activity-ktx:1.9.3"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.8.6"

    implementation "androidx.preference:preference-ktx:1.2.1"
    implementation "androidx.annotation:annotation:1.8.2"
}
